backend:
  name: github
  repo: orihachi/my-blog
  branch: main
  base_url: https://decapcms-oauth.vercel.app
  auth_endpoint: start
  site_domain: orihachi.github.io
  client_id: Ov23liV2hevPUPHNEuMm

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "ブログ記事"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日付", name: "pubDate", widget: "datetime" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }