backend:
  name: git-gateway
  branch: main  # ← あなたのデプロイ対象のブランチ（通常は main）

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

site_url: https://komu-nichijo.netlify.app
display_url: https://komu-nichijo.netlify.app

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
