backend:
  name: github
  repo: orihachi/my-blog  # ← GitHubリポジトリ名に合わせて！
  branch: main

auth:
  client_id: Ov23liV2hevPUPHNEuMm

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

site_url: https://orihachi.github.io/my-blog
display_url: https://orihachi.github.io/my-blog

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
